-- =========================================================
-- Alrehla reusable database setup
-- Run first on a fresh Supabase project.
-- Generated from the current app schema, security fixes, and RPC usage.
-- Safe to re-run for policies/functions/indexes. It is not a destructive
-- migration for databases that already have incompatible column types.
-- =========================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";


-- ---------------------------------------------------------
-- Tables
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'user' CHECK (
    role IN (
      'user', 'parent', 'student', 'instructor', 'super_admin',
      'general_supervisor', 'enha_lak_supervisor', 'creative_writing_supervisor',
      'content_editor', 'support_agent', 'publisher'
    )
  ),
  phone TEXT,
  address TEXT,
  city TEXT,
  country TEXT DEFAULT 'EG',
  governorate TEXT,
  timezone TEXT DEFAULT 'Africa/Cairo',
  currency TEXT DEFAULT 'EGP',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.child_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  student_user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  birth_date DATE NOT NULL,
  gender TEXT NOT NULL CHECK (gender IN ('ذكر', 'أنثى')),
  avatar_url TEXT,
  interests TEXT[],
  strengths TEXT[],
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.instructors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL UNIQUE REFERENCES public.profiles(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  specialty TEXT,
  bio TEXT,
  avatar_url TEXT,
  intro_video_url TEXT,
  teaching_philosophy TEXT,
  expertise_areas TEXT[],
  published_works JSONB DEFAULT '[]'::jsonb,
  rate_per_session NUMERIC(10, 2),
  package_rates JSONB DEFAULT '{}'::jsonb,
  service_rates JSONB DEFAULT '{}'::jsonb,
  weekly_schedule JSONB DEFAULT '{}'::jsonb,
  intro_availability JSONB DEFAULT '{}'::jsonb,
  availability JSONB DEFAULT '{}'::jsonb,
  schedule_status TEXT DEFAULT 'approved' CHECK (schedule_status IN ('pending', 'approved', 'rejected')),
  profile_update_status TEXT DEFAULT 'approved' CHECK (profile_update_status IN ('pending', 'approved', 'rejected')),
  pending_profile_data JSONB,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.publisher_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL UNIQUE REFERENCES public.profiles(id) ON DELETE CASCADE,
  store_name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  logo_url TEXT,
  cover_url TEXT,
  description TEXT,
  website TEXT,
  social_links JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.personalized_products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  product_type TEXT NOT NULL DEFAULT 'hero_story' CHECK (product_type IN ('hero_story', 'library_book', 'subscription_box', 'addon')),
  description TEXT,
  image_url TEXT,
  features JSONB DEFAULT '[]'::jsonb,
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_featured BOOLEAN NOT NULL DEFAULT FALSE,
  is_addon BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  has_printed_version BOOLEAN NOT NULL DEFAULT FALSE,
  price_printed NUMERIC(10, 2),
  price_electronic NUMERIC(10, 2),
  goal_config TEXT NOT NULL DEFAULT 'none' CHECK (goal_config IN ('none', 'predefined', 'custom', 'predefined_and_custom')),
  story_goals JSONB DEFAULT '[]'::jsonb,
  image_slots JSONB DEFAULT '[]'::jsonb,
  text_fields JSONB DEFAULT '[]'::jsonb,
  component_keys TEXT[],
  publisher_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  approval_status TEXT NOT NULL DEFAULT 'approved' CHECK (approval_status IN ('pending', 'approved', 'rejected')),
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.creative_writing_packages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  sessions TEXT NOT NULL,
  price NUMERIC(10, 2) NOT NULL,
  price_per_session NUMERIC(10, 2),
  description TEXT,
  detailed_description TEXT,
  features JSONB DEFAULT '[]'::jsonb,
  target_age TEXT,
  level TEXT,
  icon_name TEXT,
  popular BOOLEAN NOT NULL DEFAULT FALSE,
  comparison_values JSONB DEFAULT '{}'::jsonb,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.standalone_services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  price NUMERIC(10, 2) NOT NULL,
  description TEXT,
  category TEXT,
  icon_name TEXT,
  requires_file_upload BOOLEAN NOT NULL DEFAULT FALSE,
  provider_type TEXT DEFAULT 'company' CHECK (provider_type IN ('company', 'instructor')),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.subscription_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  duration_months INTEGER NOT NULL,
  price NUMERIC(10, 2) NOT NULL,
  price_per_month NUMERIC(10, 2),
  savings_text TEXT,
  is_best_value BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.orders (
  id TEXT PRIMARY KEY,
  user_id UUID NOT NULL,
  child_id BIGINT,
  item_summary TEXT NOT NULL,
  total NUMERIC(10, 2) NOT NULL DEFAULT 0,
  shipping_cost NUMERIC(10, 2) NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'بانتظار الدفع' CHECK (status IN ('بانتظار الدفع', 'بانتظار المراجعة', 'قيد التجهيز', 'يحتاج مراجعة', 'قيد التنفيذ', 'تم الشحن', 'تم التسليم', 'مكتمل', 'ملغي')),
  details JSONB DEFAULT '{}'::jsonb,
  admin_comment TEXT,
  receipt_url TEXT,
  order_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.subscriptions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  child_id BIGINT,
  plan_name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending_payment' CHECK (status IN ('active', 'paused', 'cancelled', 'pending_payment')),
  start_date TIMESTAMPTZ DEFAULT NOW(),
  end_date TIMESTAMPTZ,
  next_renewal_date TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.service_orders (
  id TEXT PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  child_id BIGINT REFERENCES public.child_profiles(id) ON DELETE SET NULL,
  service_id BIGINT REFERENCES public.standalone_services(id) ON DELETE SET NULL,
  assigned_instructor_id BIGINT REFERENCES public.instructors(id) ON DELETE SET NULL,
  total NUMERIC(10, 2) NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'بانتظار الدفع' CHECK (status IN ('بانتظار الدفع', 'بانتظار المراجعة', 'قيد التجهيز', 'يحتاج مراجعة', 'قيد التنفيذ', 'تم الشحن', 'تم التسليم', 'مكتمل', 'ملغي')),
  details JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.bookings (
  id TEXT PRIMARY KEY,
  user_id UUID NOT NULL,
  child_id BIGINT,
  instructor_id BIGINT,
  package_name TEXT NOT NULL,
  booking_date DATE NOT NULL,
  booking_time TEXT NOT NULL,
  total NUMERIC(10, 2) NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'بانتظار الدفع' CHECK (status IN ('بانتظار الدفع', 'مؤكد', 'مكتمل', 'ملغي', 'بانتظار المراجعة')),
  receipt_url TEXT,
  progress_notes TEXT,
  details JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.scheduled_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id TEXT REFERENCES public.bookings(id) ON DELETE CASCADE,
  subscription_id UUID REFERENCES public.subscriptions(id) ON DELETE CASCADE,
  child_id BIGINT REFERENCES public.child_profiles(id) ON DELETE SET NULL,
  instructor_id BIGINT REFERENCES public.instructors(id) ON DELETE SET NULL,
  session_date TIMESTAMPTZ NOT NULL,
  session_time TEXT,
  status TEXT NOT NULL DEFAULT 'upcoming' CHECK (status IN ('upcoming', 'completed', 'missed', 'cancelled')),
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.session_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id TEXT NOT NULL REFERENCES public.bookings(id) ON DELETE CASCADE,
  sender_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  sender_role TEXT NOT NULL,
  message_text TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.session_attachments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id TEXT NOT NULL REFERENCES public.bookings(id) ON DELETE CASCADE,
  uploader_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  uploader_role TEXT NOT NULL,
  file_name TEXT,
  file_url TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.badges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  icon_name TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.child_badges (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  child_id BIGINT NOT NULL REFERENCES public.child_profiles(id) ON DELETE CASCADE,
  badge_id BIGINT NOT NULL REFERENCES public.badges(id) ON DELETE CASCADE,
  earned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (child_id, badge_id)
);

CREATE TABLE IF NOT EXISTS public.blog_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  author_name TEXT DEFAULT 'منصة الرحلة',
  image_url TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('published', 'draft')),
  published_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.support_tickets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  subject TEXT NOT NULL,
  message TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'جديدة' CHECK (status IN ('جديدة', 'تمت المراجعة', 'مغلقة')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.join_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  role TEXT NOT NULL,
  message TEXT,
  portfolio_url TEXT,
  status TEXT NOT NULL DEFAULT 'جديد' CHECK (status IN ('جديد', 'تمت المراجعة', 'مقبول', 'مرفوض')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.support_session_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  instructor_id BIGINT REFERENCES public.instructors(id) ON DELETE SET NULL,
  child_id BIGINT REFERENCES public.child_profiles(id) ON DELETE CASCADE,
  reason TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  message TEXT NOT NULL,
  link TEXT,
  type TEXT NOT NULL DEFAULT 'info',
  read BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.site_settings (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.site_content (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section TEXT NOT NULL,
  key TEXT NOT NULL,
  value JSONB NOT NULL,
  language TEXT NOT NULL DEFAULT 'ar',
  UNIQUE (section, key, language)
);

CREATE TABLE IF NOT EXISTS public.audit_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  target_description TEXT,
  details TEXT,
  timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.instructor_payouts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  instructor_id BIGINT NOT NULL REFERENCES public.instructors(id) ON DELETE CASCADE,
  amount NUMERIC(10, 2) NOT NULL CHECK (amount >= 0),
  payout_date DATE NOT NULL DEFAULT CURRENT_DATE,
  details TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.publisher_payouts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  publisher_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  amount NUMERIC(10, 2) NOT NULL CHECK (amount >= 0),
  payout_date DATE NOT NULL DEFAULT CURRENT_DATE,
  details TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.comparison_items (
  id TEXT PRIMARY KEY,
  label TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('text', 'boolean')),
  sort_order INTEGER NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------
-- Named foreign keys expected by PostgREST relationship hints
-- ---------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_orders_user' AND conrelid = 'public.orders'::regclass) THEN
    ALTER TABLE public.orders ADD CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_orders_child' AND conrelid = 'public.orders'::regclass) THEN
    ALTER TABLE public.orders ADD CONSTRAINT fk_orders_child FOREIGN KEY (child_id) REFERENCES public.child_profiles(id) ON DELETE SET NULL;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_subscriptions_user' AND conrelid = 'public.subscriptions'::regclass) THEN
    ALTER TABLE public.subscriptions ADD CONSTRAINT fk_subscriptions_user FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_subscriptions_child' AND conrelid = 'public.subscriptions'::regclass) THEN
    ALTER TABLE public.subscriptions ADD CONSTRAINT fk_subscriptions_child FOREIGN KEY (child_id) REFERENCES public.child_profiles(id) ON DELETE SET NULL;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_bookings_user' AND conrelid = 'public.bookings'::regclass) THEN
    ALTER TABLE public.bookings ADD CONSTRAINT fk_bookings_user FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_bookings_child' AND conrelid = 'public.bookings'::regclass) THEN
    ALTER TABLE public.bookings ADD CONSTRAINT fk_bookings_child FOREIGN KEY (child_id) REFERENCES public.child_profiles(id) ON DELETE SET NULL;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_bookings_instructor' AND conrelid = 'public.bookings'::regclass) THEN
    ALTER TABLE public.bookings ADD CONSTRAINT fk_bookings_instructor FOREIGN KEY (instructor_id) REFERENCES public.instructors(id) ON DELETE SET NULL;
  END IF;
END $$;

-- ---------------------------------------------------------
-- Security helper functions
-- ---------------------------------------------------------
CREATE OR REPLACE FUNCTION public.current_user_role()
RETURNS TEXT
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT role FROM public.profiles WHERE id = auth.uid();
$$;

CREATE OR REPLACE FUNCTION public.has_role(allowed_roles TEXT[])
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE(public.current_user_role() = ANY(allowed_roles), FALSE);
$$;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT public.has_role(ARRAY['super_admin', 'general_supervisor']);
$$;

-- ---------------------------------------------------------
-- Backward-compatible column additions for partially migrated DBs
-- ---------------------------------------------------------
ALTER TABLE public.personalized_products ADD COLUMN IF NOT EXISTS price_electronic NUMERIC(10, 2);
ALTER TABLE public.personalized_products ADD COLUMN IF NOT EXISTS publisher_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL;
ALTER TABLE public.personalized_products ADD COLUMN IF NOT EXISTS approval_status TEXT NOT NULL DEFAULT 'approved';
ALTER TABLE public.personalized_products ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE public.instructors ADD COLUMN IF NOT EXISTS package_rates JSONB DEFAULT '{}'::jsonb;
ALTER TABLE public.instructors ADD COLUMN IF NOT EXISTS service_rates JSONB DEFAULT '{}'::jsonb;
ALTER TABLE public.instructors ADD COLUMN IF NOT EXISTS published_works JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.instructors ADD COLUMN IF NOT EXISTS intro_availability JSONB DEFAULT '{}'::jsonb;
ALTER TABLE public.subscription_plans ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE public.standalone_services ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE public.creative_writing_packages ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

-- ---------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_profiles_role ON public.profiles(role);
CREATE INDEX IF NOT EXISTS idx_profiles_email ON public.profiles(email);
CREATE INDEX IF NOT EXISTS idx_child_profiles_user_id ON public.child_profiles(user_id);
CREATE INDEX IF NOT EXISTS idx_child_profiles_student_user_id ON public.child_profiles(student_user_id);
CREATE INDEX IF NOT EXISTS idx_instructors_user_id ON public.instructors(user_id);
CREATE INDEX IF NOT EXISTS idx_products_key ON public.personalized_products(key);
CREATE INDEX IF NOT EXISTS idx_products_visibility ON public.personalized_products(is_active, approval_status, deleted_at);
CREATE INDEX IF NOT EXISTS idx_products_publisher_id ON public.personalized_products(publisher_id);
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON public.orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_child_id ON public.orders(child_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON public.orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_order_date ON public.orders(order_date DESC);
CREATE INDEX IF NOT EXISTS idx_bookings_user_id ON public.bookings(user_id);
CREATE INDEX IF NOT EXISTS idx_bookings_child_id ON public.bookings(child_id);
CREATE INDEX IF NOT EXISTS idx_bookings_instructor_id ON public.bookings(instructor_id);
CREATE INDEX IF NOT EXISTS idx_bookings_status ON public.bookings(status);
CREATE UNIQUE INDEX IF NOT EXISTS bookings_instructor_slot_idx ON public.bookings(instructor_id, booking_date, booking_time) WHERE status <> 'ملغي';
CREATE INDEX IF NOT EXISTS idx_subscriptions_user_id ON public.subscriptions(user_id);
CREATE INDEX IF NOT EXISTS idx_service_orders_user_id ON public.service_orders(user_id);
CREATE INDEX IF NOT EXISTS idx_service_orders_instructor_id ON public.service_orders(assigned_instructor_id);
CREATE INDEX IF NOT EXISTS idx_scheduled_sessions_booking_id ON public.scheduled_sessions(booking_id);
CREATE INDEX IF NOT EXISTS idx_scheduled_sessions_child_id ON public.scheduled_sessions(child_id);
CREATE INDEX IF NOT EXISTS idx_scheduled_sessions_instructor_id ON public.scheduled_sessions(instructor_id);
CREATE INDEX IF NOT EXISTS idx_session_messages_booking_id ON public.session_messages(booking_id);
CREATE INDEX IF NOT EXISTS idx_session_attachments_booking_id ON public.session_attachments(booking_id);
CREATE INDEX IF NOT EXISTS idx_blog_posts_status ON public.blog_posts(status);
CREATE INDEX IF NOT EXISTS idx_blog_posts_slug ON public.blog_posts(slug);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON public.notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_read ON public.notifications(read);
CREATE INDEX IF NOT EXISTS idx_audit_logs_timestamp ON public.audit_logs(timestamp DESC);

-- ---------------------------------------------------------
-- Timestamp triggers and profile/product guards
-- ---------------------------------------------------------
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.prevent_profile_role_escalation()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Trusted SQL setup/service-role runs do not have auth.uid(); browser/API calls do.
  IF auth.uid() IS NULL OR public.is_admin() THEN
    RETURN NEW;
  END IF;

  IF TG_OP = 'INSERT' AND NEW.role NOT IN ('user', 'parent', 'student') THEN
    RAISE EXCEPTION 'Not authorized to create privileged profile role';
  END IF;

  IF TG_OP = 'UPDATE' AND NEW.role IS DISTINCT FROM OLD.role THEN
    RAISE EXCEPTION 'Not authorized to change profile role';
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.force_product_pending_status()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF public.current_user_role() = 'publisher' AND NOT public.has_role(ARRAY['super_admin', 'general_supervisor', 'enha_lak_supervisor']) THEN
    NEW.approval_status := 'pending';
    NEW.is_active := FALSE;
    NEW.publisher_id := auth.uid();
  END IF;
  RETURN NEW;
END;
$$;

DO $$
DECLARE
  target_table TEXT;
BEGIN
  FOREACH target_table IN ARRAY ARRAY[
    'profiles', 'child_profiles', 'instructors', 'publisher_profiles',
    'personalized_products', 'creative_writing_packages', 'standalone_services',
    'subscription_plans', 'orders', 'subscriptions', 'service_orders', 'bookings',
    'scheduled_sessions', 'blog_posts', 'support_tickets', 'join_requests',
    'support_session_requests'
  ] LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS update_%s_updated_at ON public.%I', target_table, target_table);
    EXECUTE format('CREATE TRIGGER update_%s_updated_at BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column()', target_table, target_table);
  END LOOP;
END $$;

DROP TRIGGER IF EXISTS prevent_profile_role_escalation_trigger ON public.profiles;
CREATE TRIGGER prevent_profile_role_escalation_trigger
BEFORE INSERT OR UPDATE ON public.profiles
FOR EACH ROW EXECUTE FUNCTION public.prevent_profile_role_escalation();

DROP TRIGGER IF EXISTS tr_force_product_pending ON public.personalized_products;
CREATE TRIGGER tr_force_product_pending
BEFORE INSERT OR UPDATE ON public.personalized_products
FOR EACH ROW EXECUTE FUNCTION public.force_product_pending_status();

-- ---------------------------------------------------------
-- Safe public views
-- ---------------------------------------------------------
CREATE OR REPLACE VIEW public.public_profiles AS
SELECT id, name, role FROM public.profiles;

CREATE OR REPLACE VIEW public.public_settings AS
SELECT key, value
FROM public.site_settings
WHERE key IN (
  'prices', 'branding', 'shipping_costs', 'global_content', 'social_links',
  'communication_settings', 'pricing_config', 'maintenance_settings',
  'library_pricing_config', 'jitsi_settings'
);

GRANT SELECT ON public.public_profiles TO anon, authenticated;
GRANT SELECT ON public.public_settings TO anon, authenticated;

-- ---------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.child_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.instructors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.publisher_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.personalized_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.creative_writing_packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.standalone_services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscription_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scheduled_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.session_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.session_attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.badges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.child_badges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blog_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.join_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_session_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_content ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.instructor_payouts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.publisher_payouts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comparison_items ENABLE ROW LEVEL SECURITY;

-- Drop old and replacement policies by stable names.
DROP POLICY IF EXISTS profiles_select_own_or_admin ON public.profiles;
DROP POLICY IF EXISTS profiles_insert_self_safe_role ON public.profiles;
DROP POLICY IF EXISTS profiles_update_self_or_admin ON public.profiles;
DROP POLICY IF EXISTS profiles_admin_delete ON public.profiles;
CREATE POLICY profiles_select_own_or_admin ON public.profiles FOR SELECT USING (id = auth.uid() OR public.is_admin());
CREATE POLICY profiles_insert_self_safe_role ON public.profiles FOR INSERT WITH CHECK (id = auth.uid() AND role IN ('user', 'parent', 'student'));
CREATE POLICY profiles_update_self_or_admin ON public.profiles FOR UPDATE USING (id = auth.uid() OR public.is_admin()) WITH CHECK (id = auth.uid() OR public.is_admin());
CREATE POLICY profiles_admin_delete ON public.profiles FOR DELETE USING (public.is_admin());

DROP POLICY IF EXISTS child_profiles_manage_owner_or_admin ON public.child_profiles;
CREATE POLICY child_profiles_manage_owner_or_admin ON public.child_profiles FOR ALL USING (
  user_id = auth.uid() OR student_user_id = auth.uid() OR public.is_admin()
) WITH CHECK (user_id = auth.uid() OR public.is_admin());

DROP POLICY IF EXISTS instructors_public_read ON public.instructors;
DROP POLICY IF EXISTS instructors_owner_or_admin_manage ON public.instructors;
CREATE POLICY instructors_public_read ON public.instructors FOR SELECT USING (deleted_at IS NULL OR public.is_admin() OR user_id = auth.uid());
CREATE POLICY instructors_owner_or_admin_manage ON public.instructors FOR ALL USING (user_id = auth.uid() OR public.is_admin()) WITH CHECK (user_id = auth.uid() OR public.is_admin());

DROP POLICY IF EXISTS publisher_profiles_public_read ON public.publisher_profiles;
DROP POLICY IF EXISTS publisher_profiles_owner_or_admin_manage ON public.publisher_profiles;
CREATE POLICY publisher_profiles_public_read ON public.publisher_profiles FOR SELECT USING (TRUE);
CREATE POLICY publisher_profiles_owner_or_admin_manage ON public.publisher_profiles FOR ALL USING (user_id = auth.uid() OR public.is_admin()) WITH CHECK (user_id = auth.uid() OR public.is_admin());

DROP POLICY IF EXISTS products_strict_visibility ON public.personalized_products;
DROP POLICY IF EXISTS products_admin_manage ON public.personalized_products;
DROP POLICY IF EXISTS products_publishers_manage_own ON public.personalized_products;
CREATE POLICY products_strict_visibility ON public.personalized_products FOR SELECT USING (
  public.has_role(ARRAY['super_admin', 'general_supervisor', 'enha_lak_supervisor'])
  OR publisher_id = auth.uid()
  OR (is_active = TRUE AND approval_status = 'approved' AND deleted_at IS NULL)
);
CREATE POLICY products_admin_manage ON public.personalized_products FOR ALL USING (public.has_role(ARRAY['super_admin', 'general_supervisor', 'enha_lak_supervisor'])) WITH CHECK (public.has_role(ARRAY['super_admin', 'general_supervisor', 'enha_lak_supervisor']));
CREATE POLICY products_publishers_manage_own ON public.personalized_products FOR ALL USING (publisher_id = auth.uid() AND public.current_user_role() = 'publisher') WITH CHECK (publisher_id = auth.uid() AND public.current_user_role() = 'publisher');

DROP POLICY IF EXISTS packages_public_read ON public.creative_writing_packages;
DROP POLICY IF EXISTS packages_admin_manage ON public.creative_writing_packages;
CREATE POLICY packages_public_read ON public.creative_writing_packages FOR SELECT USING (deleted_at IS NULL AND is_active = TRUE OR public.is_admin());
CREATE POLICY packages_admin_manage ON public.creative_writing_packages FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS standalone_services_public_read ON public.standalone_services;
DROP POLICY IF EXISTS standalone_services_admin_manage ON public.standalone_services;
CREATE POLICY standalone_services_public_read ON public.standalone_services FOR SELECT USING (deleted_at IS NULL AND is_active = TRUE OR public.is_admin());
CREATE POLICY standalone_services_admin_manage ON public.standalone_services FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS subscription_plans_public_read ON public.subscription_plans;
DROP POLICY IF EXISTS subscription_plans_admin_manage ON public.subscription_plans;
CREATE POLICY subscription_plans_public_read ON public.subscription_plans FOR SELECT USING (deleted_at IS NULL AND is_active = TRUE OR public.is_admin());
CREATE POLICY subscription_plans_admin_manage ON public.subscription_plans FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS orders_related_read ON public.orders;
DROP POLICY IF EXISTS orders_user_insert ON public.orders;
DROP POLICY IF EXISTS orders_owner_update_receipt_or_admin ON public.orders;
DROP POLICY IF EXISTS orders_admin_delete ON public.orders;
CREATE POLICY orders_related_read ON public.orders FOR SELECT USING (user_id = auth.uid() OR public.has_role(ARRAY['super_admin', 'general_supervisor', 'enha_lak_supervisor', 'creative_writing_supervisor']));
CREATE POLICY orders_user_insert ON public.orders FOR INSERT WITH CHECK (user_id = auth.uid() OR public.is_admin());
CREATE POLICY orders_owner_update_receipt_or_admin ON public.orders FOR UPDATE USING (user_id = auth.uid() OR public.is_admin()) WITH CHECK (user_id = auth.uid() OR public.is_admin());
CREATE POLICY orders_admin_delete ON public.orders FOR DELETE USING (public.is_admin());

DROP POLICY IF EXISTS subscriptions_related_manage ON public.subscriptions;
CREATE POLICY subscriptions_related_manage ON public.subscriptions FOR ALL USING (user_id = auth.uid() OR public.is_admin()) WITH CHECK (user_id = auth.uid() OR public.is_admin());

DROP POLICY IF EXISTS service_orders_related_read ON public.service_orders;
DROP POLICY IF EXISTS service_orders_owner_insert ON public.service_orders;
DROP POLICY IF EXISTS service_orders_owner_or_admin_update ON public.service_orders;
CREATE POLICY service_orders_related_read ON public.service_orders FOR SELECT USING (
  user_id = auth.uid()
  OR public.has_role(ARRAY['super_admin', 'general_supervisor', 'creative_writing_supervisor'])
  OR EXISTS (SELECT 1 FROM public.instructors i WHERE i.id = service_orders.assigned_instructor_id AND i.user_id = auth.uid())
);
CREATE POLICY service_orders_owner_insert ON public.service_orders FOR INSERT WITH CHECK (user_id = auth.uid() OR public.is_admin());
CREATE POLICY service_orders_owner_or_admin_update ON public.service_orders FOR UPDATE USING (user_id = auth.uid() OR public.is_admin()) WITH CHECK (user_id = auth.uid() OR public.is_admin());

DROP POLICY IF EXISTS bookings_related_read ON public.bookings;
DROP POLICY IF EXISTS bookings_owner_insert ON public.bookings;
DROP POLICY IF EXISTS bookings_related_update ON public.bookings;
CREATE POLICY bookings_related_read ON public.bookings FOR SELECT USING (
  user_id = auth.uid()
  OR public.is_admin()
  OR EXISTS (SELECT 1 FROM public.instructors i WHERE i.id = bookings.instructor_id AND i.user_id = auth.uid())
);
CREATE POLICY bookings_owner_insert ON public.bookings FOR INSERT WITH CHECK (user_id = auth.uid() OR public.is_admin());
CREATE POLICY bookings_related_update ON public.bookings FOR UPDATE USING (
  user_id = auth.uid()
  OR public.is_admin()
  OR EXISTS (SELECT 1 FROM public.instructors i WHERE i.id = bookings.instructor_id AND i.user_id = auth.uid())
) WITH CHECK (
  user_id = auth.uid()
  OR public.is_admin()
  OR EXISTS (SELECT 1 FROM public.instructors i WHERE i.id = bookings.instructor_id AND i.user_id = auth.uid())
);

DROP POLICY IF EXISTS scheduled_sessions_related_read ON public.scheduled_sessions;
DROP POLICY IF EXISTS scheduled_sessions_admin_or_instructor_manage ON public.scheduled_sessions;
CREATE POLICY scheduled_sessions_related_read ON public.scheduled_sessions FOR SELECT USING (
  public.is_admin()
  OR EXISTS (SELECT 1 FROM public.bookings b WHERE b.id = scheduled_sessions.booking_id AND b.user_id = auth.uid())
  OR EXISTS (SELECT 1 FROM public.instructors i WHERE i.id = scheduled_sessions.instructor_id AND i.user_id = auth.uid())
  OR EXISTS (SELECT 1 FROM public.child_profiles c WHERE c.id = scheduled_sessions.child_id AND c.student_user_id = auth.uid())
);
CREATE POLICY scheduled_sessions_admin_or_instructor_manage ON public.scheduled_sessions FOR ALL USING (
  public.is_admin() OR EXISTS (SELECT 1 FROM public.instructors i WHERE i.id = scheduled_sessions.instructor_id AND i.user_id = auth.uid())
) WITH CHECK (
  public.is_admin() OR EXISTS (SELECT 1 FROM public.instructors i WHERE i.id = scheduled_sessions.instructor_id AND i.user_id = auth.uid())
);

DROP POLICY IF EXISTS session_messages_related_read ON public.session_messages;
DROP POLICY IF EXISTS session_messages_sender_insert ON public.session_messages;
CREATE POLICY session_messages_related_read ON public.session_messages FOR SELECT USING (
  public.is_admin()
  OR EXISTS (SELECT 1 FROM public.bookings b WHERE b.id = session_messages.booking_id AND b.user_id = auth.uid())
  OR EXISTS (SELECT 1 FROM public.bookings b JOIN public.instructors i ON i.id = b.instructor_id WHERE b.id = session_messages.booking_id AND i.user_id = auth.uid())
);
CREATE POLICY session_messages_sender_insert ON public.session_messages FOR INSERT WITH CHECK (sender_id = auth.uid());

DROP POLICY IF EXISTS session_attachments_related_read ON public.session_attachments;
DROP POLICY IF EXISTS session_attachments_uploader_insert ON public.session_attachments;
CREATE POLICY session_attachments_related_read ON public.session_attachments FOR SELECT USING (
  public.is_admin()
  OR EXISTS (SELECT 1 FROM public.bookings b WHERE b.id = session_attachments.booking_id AND b.user_id = auth.uid())
  OR EXISTS (SELECT 1 FROM public.bookings b JOIN public.instructors i ON i.id = b.instructor_id WHERE b.id = session_attachments.booking_id AND i.user_id = auth.uid())
);
CREATE POLICY session_attachments_uploader_insert ON public.session_attachments FOR INSERT WITH CHECK (uploader_id = auth.uid());

DROP POLICY IF EXISTS badges_public_read ON public.badges;
DROP POLICY IF EXISTS badges_admin_manage ON public.badges;
CREATE POLICY badges_public_read ON public.badges FOR SELECT USING (TRUE);
CREATE POLICY badges_admin_manage ON public.badges FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS child_badges_related_read ON public.child_badges;
DROP POLICY IF EXISTS child_badges_admin_or_instructor_insert ON public.child_badges;
CREATE POLICY child_badges_related_read ON public.child_badges FOR SELECT USING (
  public.is_admin()
  OR EXISTS (SELECT 1 FROM public.child_profiles c WHERE c.id = child_badges.child_id AND (c.user_id = auth.uid() OR c.student_user_id = auth.uid()))
);
CREATE POLICY child_badges_admin_or_instructor_insert ON public.child_badges FOR INSERT WITH CHECK (public.is_admin() OR public.current_user_role() = 'instructor');

DROP POLICY IF EXISTS blog_posts_public_read_published ON public.blog_posts;
DROP POLICY IF EXISTS blog_posts_editor_manage ON public.blog_posts;
CREATE POLICY blog_posts_public_read_published ON public.blog_posts FOR SELECT USING ((status = 'published' AND deleted_at IS NULL) OR public.has_role(ARRAY['super_admin', 'general_supervisor', 'content_editor']));
CREATE POLICY blog_posts_editor_manage ON public.blog_posts FOR ALL USING (public.has_role(ARRAY['super_admin', 'general_supervisor', 'content_editor'])) WITH CHECK (public.has_role(ARRAY['super_admin', 'general_supervisor', 'content_editor']));

DROP POLICY IF EXISTS support_tickets_public_insert ON public.support_tickets;
DROP POLICY IF EXISTS support_tickets_staff_manage ON public.support_tickets;
CREATE POLICY support_tickets_public_insert ON public.support_tickets FOR INSERT WITH CHECK (TRUE);
CREATE POLICY support_tickets_staff_manage ON public.support_tickets FOR ALL USING (public.has_role(ARRAY['super_admin', 'general_supervisor', 'support_agent'])) WITH CHECK (public.has_role(ARRAY['super_admin', 'general_supervisor', 'support_agent']));

DROP POLICY IF EXISTS join_requests_public_insert ON public.join_requests;
DROP POLICY IF EXISTS join_requests_staff_manage ON public.join_requests;
CREATE POLICY join_requests_public_insert ON public.join_requests FOR INSERT WITH CHECK (TRUE);
CREATE POLICY join_requests_staff_manage ON public.join_requests FOR ALL USING (public.has_role(ARRAY['super_admin', 'general_supervisor', 'support_agent'])) WITH CHECK (public.has_role(ARRAY['super_admin', 'general_supervisor', 'support_agent']));

DROP POLICY IF EXISTS support_session_requests_related_manage ON public.support_session_requests;
CREATE POLICY support_session_requests_related_manage ON public.support_session_requests FOR ALL USING (
  public.is_admin()
  OR EXISTS (SELECT 1 FROM public.instructors i WHERE i.id = support_session_requests.instructor_id AND i.user_id = auth.uid())
) WITH CHECK (
  public.is_admin()
  OR EXISTS (SELECT 1 FROM public.instructors i WHERE i.id = support_session_requests.instructor_id AND i.user_id = auth.uid())
);

DROP POLICY IF EXISTS notifications_owner_read_update_delete ON public.notifications;
DROP POLICY IF EXISTS notifications_authenticated_insert ON public.notifications;
CREATE POLICY notifications_owner_read_update_delete ON public.notifications FOR SELECT USING (user_id = auth.uid());
CREATE POLICY notifications_authenticated_insert ON public.notifications FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS notifications_owner_update ON public.notifications;
CREATE POLICY notifications_owner_update ON public.notifications FOR UPDATE USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
DROP POLICY IF EXISTS notifications_owner_delete ON public.notifications;
CREATE POLICY notifications_owner_delete ON public.notifications FOR DELETE USING (user_id = auth.uid());

DROP POLICY IF EXISTS site_settings_admin_select ON public.site_settings;
DROP POLICY IF EXISTS site_settings_admin_manage ON public.site_settings;
CREATE POLICY site_settings_admin_select ON public.site_settings FOR SELECT USING (public.is_admin());
CREATE POLICY site_settings_admin_manage ON public.site_settings FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
REVOKE ALL ON public.site_settings FROM anon, authenticated;

DROP POLICY IF EXISTS site_content_public_read ON public.site_content;
DROP POLICY IF EXISTS site_content_admin_manage ON public.site_content;
CREATE POLICY site_content_public_read ON public.site_content FOR SELECT USING (TRUE);
CREATE POLICY site_content_admin_manage ON public.site_content FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS audit_logs_admin_read ON public.audit_logs;
DROP POLICY IF EXISTS audit_logs_authenticated_insert_own ON public.audit_logs;
CREATE POLICY audit_logs_admin_read ON public.audit_logs FOR SELECT USING (public.is_admin());
CREATE POLICY audit_logs_authenticated_insert_own ON public.audit_logs FOR INSERT WITH CHECK (auth.uid() IS NOT NULL AND (user_id IS NULL OR user_id = auth.uid()));

DROP POLICY IF EXISTS instructor_payouts_admin_manage ON public.instructor_payouts;
DROP POLICY IF EXISTS instructor_payouts_instructor_read_own ON public.instructor_payouts;
CREATE POLICY instructor_payouts_admin_manage ON public.instructor_payouts FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY instructor_payouts_instructor_read_own ON public.instructor_payouts FOR SELECT USING (EXISTS (SELECT 1 FROM public.instructors i WHERE i.id = instructor_payouts.instructor_id AND i.user_id = auth.uid()));

DROP POLICY IF EXISTS publisher_payouts_admin_manage ON public.publisher_payouts;
DROP POLICY IF EXISTS publisher_payouts_publisher_read_own ON public.publisher_payouts;
CREATE POLICY publisher_payouts_admin_manage ON public.publisher_payouts FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY publisher_payouts_publisher_read_own ON public.publisher_payouts FOR SELECT USING (publisher_id = auth.uid());

DROP POLICY IF EXISTS comparison_items_public_read ON public.comparison_items;
DROP POLICY IF EXISTS comparison_items_admin_manage ON public.comparison_items;
CREATE POLICY comparison_items_public_read ON public.comparison_items FOR SELECT USING (TRUE);
CREATE POLICY comparison_items_admin_manage ON public.comparison_items FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- ---------------------------------------------------------
-- Storage bucket and storage.objects policies
-- ---------------------------------------------------------
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('receipts', 'receipts', FALSE, 10485760, ARRAY['image/png', 'image/jpeg', 'image/jpg', 'application/pdf'])
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

DROP POLICY IF EXISTS receipts_authenticated_upload_limited ON storage.objects;
DROP POLICY IF EXISTS receipts_related_read ON storage.objects;
DROP POLICY IF EXISTS receipts_owner_delete ON storage.objects;
CREATE POLICY receipts_authenticated_upload_limited ON storage.objects
FOR INSERT TO authenticated
WITH CHECK (
  bucket_id = 'receipts'
);
CREATE POLICY receipts_related_read ON storage.objects
FOR SELECT TO authenticated
USING (bucket_id = 'receipts');
CREATE POLICY receipts_owner_delete ON storage.objects
FOR DELETE TO authenticated
USING (bucket_id = 'receipts' AND owner = auth.uid());

-- ---------------------------------------------------------
-- RPCs used by the app
-- ---------------------------------------------------------
CREATE OR REPLACE FUNCTION public.reload_schema_cache()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  NOTIFY pgrst, 'reload config';
END;
$$;

CREATE OR REPLACE FUNCTION public.create_order_secure(
  p_user_id UUID,
  p_child_id BIGINT,
  p_cart_items JSONB,
  p_receipt_url TEXT,
  p_shipping_address JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_order_id TEXT;
  v_service_order_id TEXT;
  v_total NUMERIC(10, 2) := 0;
  v_shipping_cost NUMERIC(10, 2) := 0;
  v_item JSONB;
  v_price NUMERIC(10, 2) := 0;
  v_summary TEXT := '';
  v_details JSONB := '{}'::jsonb;
  v_shipping_config JSONB;
  v_gov TEXT;
  v_product_key TEXT;
  v_service_id BIGINT;
  v_assigned_instructor_id BIGINT;
  v_plan_price NUMERIC(10, 2);
  v_plan_duration INTEGER;
  v_subscription_id UUID;
  v_order JSONB;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Not authorized';
  END IF;

  IF p_user_id <> auth.uid() AND NOT public.is_admin() THEN
    RAISE EXCEPTION 'Not authorized to create order for another user';
  END IF;

  IF p_child_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.child_profiles c WHERE c.id = p_child_id AND (c.user_id = p_user_id OR public.is_admin())
  ) THEN
    RAISE EXCEPTION 'Child profile does not belong to user';
  END IF;

  v_gov := COALESCE(p_shipping_address->>'governorate', p_shipping_address->>'city');
  SELECT value INTO v_shipping_config FROM public.site_settings WHERE key = 'shipping_costs';

  FOR v_item IN SELECT * FROM jsonb_array_elements(COALESCE(p_cart_items, '[]'::jsonb)) LOOP
    v_product_key := COALESCE(v_item->>'productKey', v_item->'details'->>'productKey');
    IF v_summary <> '' THEN
      v_summary := v_summary || ', ';
    END IF;
    v_summary := v_summary || COALESCE(v_item->>'summary', v_product_key, v_item->>'planName', 'طلب');

    IF v_item->>'type' = 'subscription' THEN
      SELECT price, duration_months INTO v_plan_price, v_plan_duration
      FROM public.subscription_plans
      WHERE name = COALESCE(v_item->>'planName', v_item->'details'->>'planName')
        AND deleted_at IS NULL;

      IF v_plan_price IS NULL THEN
        RAISE EXCEPTION 'Subscription plan not found';
      END IF;

      v_total := v_total + v_plan_price;
      v_subscription_id := COALESCE(NULLIF(v_item->'details'->>'subscriptionId', '')::uuid, gen_random_uuid());

      INSERT INTO public.subscriptions (id, user_id, child_id, plan_name, status, start_date, end_date, next_renewal_date)
      VALUES (
        v_subscription_id,
        p_user_id,
        p_child_id,
        COALESCE(v_item->>'planName', v_item->'details'->>'planName'),
        'pending_payment',
        NOW(),
        NOW() + make_interval(months => COALESCE(v_plan_duration, 1)),
        NOW() + INTERVAL '1 month'
      )
      ON CONFLICT (id) DO UPDATE SET status = 'pending_payment', updated_at = NOW();

      v_details := v_details || jsonb_build_object('subscriptionId', v_subscription_id);
    ELSE
      v_service_id := NULLIF(v_item->'details'->>'serviceId', '')::bigint;
      IF v_service_id IS NOT NULL OR v_product_key LIKE 'service_%' THEN
        SELECT price INTO v_price FROM public.standalone_services WHERE id = v_service_id AND deleted_at IS NULL;
        IF v_price IS NULL THEN
          RAISE EXCEPTION 'Standalone service not found';
        END IF;

        v_total := v_total + v_price;
        v_assigned_instructor_id := NULLIF(v_item->'details'->>'assigned_instructor_id', '')::bigint;
        v_service_order_id := 'SVC-' || upper(substr(md5(random()::text || clock_timestamp()::text), 1, 10));
        INSERT INTO public.service_orders (id, user_id, child_id, service_id, assigned_instructor_id, total, status, details)
        VALUES (
          v_service_order_id,
          p_user_id,
          p_child_id,
          v_service_id,
          v_assigned_instructor_id,
          v_price,
          CASE WHEN COALESCE(p_receipt_url, '') <> '' THEN 'بانتظار المراجعة' ELSE 'بانتظار الدفع' END,
          COALESCE(v_item->'details', '{}'::jsonb)
        );
      ELSE
        SELECT CASE WHEN COALESCE(v_item->'details'->>'format', '') = 'printed' THEN price_printed ELSE price_electronic END
        INTO v_price
        FROM public.personalized_products
        WHERE key = v_product_key
          AND deleted_at IS NULL
          AND is_active = TRUE
          AND approval_status = 'approved';

        IF v_price IS NULL THEN
          RAISE EXCEPTION 'Personalized product not found or inactive';
        END IF;

        v_total := v_total + v_price;

        IF COALESCE(v_item->'details'->>'format', '') = 'printed' AND v_gov IS NOT NULL THEN
          v_shipping_cost := v_shipping_cost + COALESCE(
            NULLIF(v_shipping_config->>'default', '')::numeric,
            NULLIF(v_shipping_config->>'باقي المحافظات', '')::numeric,
            0
          );
        END IF;
      END IF;
    END IF;
  END LOOP;

  IF v_summary = '' THEN
    RAISE EXCEPTION 'Cart is empty';
  END IF;

  v_order_id := 'ORD-' || upper(substr(md5(random()::text || clock_timestamp()::text), 1, 10));

  INSERT INTO public.orders (id, user_id, child_id, item_summary, total, shipping_cost, status, details, receipt_url, order_date)
  VALUES (
    v_order_id,
    p_user_id,
    p_child_id,
    v_summary,
    v_total + v_shipping_cost,
    v_shipping_cost,
    CASE WHEN COALESCE(p_receipt_url, '') <> '' THEN 'بانتظار المراجعة' ELSE 'بانتظار الدفع' END,
    jsonb_build_object('cartItems', p_cart_items, 'shippingAddress', COALESCE(p_shipping_address, '{}'::jsonb)) || v_details,
    NULLIF(p_receipt_url, ''),
    NOW()
  )
  RETURNING jsonb_build_object(
    'id', id,
    'user_id', user_id,
    'child_id', child_id,
    'item_summary', item_summary,
    'total', total,
    'shipping_cost', shipping_cost,
    'status', status,
    'details', details,
    'receipt_url', receipt_url,
    'order_date', order_date
  ) INTO v_order;

  RETURN v_order;
END;
$$;

CREATE OR REPLACE FUNCTION public.create_booking_secure(
  p_user_id UUID,
  p_child_id BIGINT,
  p_instructor_id BIGINT,
  p_package_name TEXT,
  p_booking_date DATE,
  p_booking_time TEXT,
  p_receipt_url TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_booking_id TEXT;
  v_price NUMERIC(10, 2) := 0;
  v_status TEXT;
  v_booking JSONB;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Not authorized';
  END IF;

  IF p_user_id <> auth.uid() AND NOT public.is_admin() THEN
    RAISE EXCEPTION 'Not authorized to create booking for another user';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.child_profiles c WHERE c.id = p_child_id AND (c.user_id = p_user_id OR public.is_admin())) THEN
    RAISE EXCEPTION 'Child profile does not belong to user';
  END IF;

  IF p_package_name = 'الجلسة التعريفية' THEN
    v_price := 0;
  ELSE
    SELECT price INTO v_price
    FROM public.creative_writing_packages
    WHERE name = p_package_name AND deleted_at IS NULL AND is_active = TRUE;

    IF v_price IS NULL THEN
      RAISE EXCEPTION 'Creative writing package not found';
    END IF;
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.bookings
    WHERE instructor_id = p_instructor_id
      AND booking_date = p_booking_date
      AND booking_time = p_booking_time
      AND status <> 'ملغي'
  ) THEN
    RAISE EXCEPTION 'هذا الموعد محجوز بالفعل مع هذا المدرب.';
  END IF;

  v_status := CASE WHEN v_price = 0 THEN 'مؤكد' WHEN COALESCE(p_receipt_url, '') <> '' THEN 'بانتظار المراجعة' ELSE 'بانتظار الدفع' END;
  v_booking_id := 'BKG-' || upper(substr(md5(random()::text || clock_timestamp()::text), 1, 10));

  INSERT INTO public.bookings (id, user_id, child_id, instructor_id, package_name, booking_date, booking_time, total, status, receipt_url)
  VALUES (v_booking_id, p_user_id, p_child_id, p_instructor_id, p_package_name, p_booking_date, p_booking_time, v_price, v_status, NULLIF(p_receipt_url, ''))
  RETURNING jsonb_build_object(
    'id', id,
    'user_id', user_id,
    'child_id', child_id,
    'instructor_id', instructor_id,
    'package_name', package_name,
    'booking_date', booking_date,
    'booking_time', booking_time,
    'total', total,
    'status', status,
    'receipt_url', receipt_url,
    'created_at', created_at
  ) INTO v_booking;

  RETURN v_booking;
END;
$$;

-- Compatibility stub: password resets must use Supabase Admin API in a server/Edge function.
CREATE OR REPLACE FUNCTION public.reset_student_password(target_student_id UUID, new_password TEXT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RAISE EXCEPTION 'Not authorized: reset_student_password must be implemented in a secure server function using the Supabase Admin API';
END;
$$;

GRANT EXECUTE ON FUNCTION public.reload_schema_cache() TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_order_secure(UUID, BIGINT, JSONB, TEXT, JSONB) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_booking_secure(UUID, BIGINT, BIGINT, TEXT, DATE, TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reset_student_password(UUID, TEXT) TO authenticated;

NOTIFY pgrst, 'reload config';
